### ISSUE TITLE
Error 400 when creating a new address

### ISSUE THREAD

**Issue by Abilene-may** [Fat-Blue-Cat/CDTN_BACKEND_ECOMMERCE#3]
![Image](https://github.com/Fat-Blue-Cat/CDTN_BACKEND_ECOMMERCE/assets/107451757/7cb8b959-92e6-4918-80b3-35d78ea4dbef)

![Image](https://github.com/Fat-Blue-Cat/CDTN_BACKEND_ECOMMERCE/assets/107451757/1655dcb9-a418-43ba-82f1-30428f903091)

![Image](https://github.com/Fat-Blue-Cat/CDTN_BACKEND_ECOMMERCE/assets/107451757/bf6abc88-9f44-4022-874c-551202ea037b)

**Comment by Fat-Blue-Cat** [comment]
token expired so you can not call api, please logout and login after try again
